title: Nidharsan Reddy.P
logo: https://github.com/nidharsan/Resume/blob/main/WhatsApp%20Image%202024-02-28%20at%206.27.18%20PM.jpeg
description: Data Analyst
show_downloads: true
theme: jekyll-theme-minimal
