title: Nidharsan Reddy.P
logo: /WhatsApp Image 2024-02-28 at 6.27.18 PM.jpeg
description: |
  Welcome to my digital domain. I am Nidharsan Reddy.P, a dedicated individual passionate about leveraging data for business analytics.Proficient in Python, Azure, Power BI, R, and SQL, I excel in team management With experience as a shift lead, I've demonstrated my ability to effectively coordinate and manage teams, ensuring smooth operations and timely project delivery.
show_downloads: true
theme: jekyll-theme-minimal
author:
  name: Nidharsan Reddy.P
social_links:
  - platform: github
    url: https://github.com/nidharsan
    icon: github
  - platform: linkedin
    url: https://www.linkedin.com/in/nidharsan-reddy-p-a204771b9/
    icon: linkedin
css: |
  .site-logo img {
    border-radius: 50%;
    width: 200px; /* Adjust size as needed */
    height: 200px; /* Adjust size as needed */
    object-fit: cover;
  }
